image: docker:git
services:
  - docker:dind

stages:
- build
- deploy

build:
  image: docker:dind
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master

# requires RANCHER_ACCESS_KEY, RANCHER_SECRET_KEY and to be present in gitlab project secret variables.
deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment rakettlab --service $CI_COMMIT_REF_NAME --stack kateweb --new-image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --start-before-stopping --wait-for-upgrade-to-finish
  only:
    - master